name: Build and Upload SDK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List files
      run: ls -R

    # 2. Set up Java
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'


    # 3. Build the JAR using Gradle
    - name: Build JAR
      working-directory: testSDK1
      run: ./gradlew clean build

    - name: Calculate Path
      id: calculate_path
      run: |
        # Define group info
        GROUP_ID="sdk/javaSDK"
        
        # Compute date in dd-mm-yyyy_hh-mm-ss format
        DATE=$(date +"%d-%m-%Y_%H-%M-%S")

        # Compute reusable base upload path (directory only)
        JFROG_BASE_PATH="${GROUP_ID}/${VERSION}/${DATE}"

        echo "jfrog_path=$JFROG_BASE_PATH" >> $GITHUB_OUTPUT


    # 4. Upload to JFrog Artifactory
    - name: Upload JAR to JFrog
      working-directory: testSDK1
      env:
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        ARTIFACTORY_REPO: ${{ secrets.ARTIFACTORY_REPO }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      run: |
        JAR_FILE=$(find build/libs -name "*.jar" | head -n 1)
        echo "Uploading $JAR_FILE to Artifactory..."
        curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
             -T $JAR_FILE \
             $ARTIFACTORY_URL/$ARTIFACTORY_REPO/$JFROG_BASE_PATH/$(basename $JAR_FILE)

      # After successful upload trigger Android SDK Workflow
    - name: Trigger Repo B workflow using Repository Dispatch
      uses: actions/github-script@v7
      with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.request('POST /repos/{owner}/{repo}/dispatches', {
              owner: 'Ahmed-H-Kamal',
              repo: 'testSDK2',
              event_type: 'step-sdk-external-java-v2xsdk4javav2-completed',
              client_payload: {
                source_repo: process.env.GITHUB_REPOSITORY,
                source_run: process.env.GITHUB_RUN_ID
              }
            });


    # - name: Trigger Repo 2 workflow
    #   uses: peter-evans/repository-dispatch@v2
    #   with:
    #       token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    #       repository: Ahmed-H-Kamal/testSDK2
    #       event-type: testSDK1-completed
    #       client-payload: '{"ref": "${{ github.ref }}"}'